name: 📄 Documentation
description: Have you found an issue in the documentation? You can use this one!
title: '[DOCS] <description>'
labels: ['documentation']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the question or issue. Also, make sure to include what you tried and what did not work.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots if applicable
    validations:
      required: false
