name: ❗ Other
description: Use this for any other issues. Please DO NOT create any blank issue.
title: '[OTHER] <description>'
labels: ['other']
body:
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
